on:
  - push
  - pull_request
jobs:
  compile-sketch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/compile-sketches@v1
        with:
          sketch-paths: |
            - sketches/final_code_interactive
          libraries: |
            # No libraries necessary
            - 
